### ISSUE TITLE
Add support for border color and variants 

### ISSUE THREAD

**Issue by florianbouvot** [soueuls/tailwind-color-alpha#1]
Hi,

Can you add support for `border-color`and variants like `hover`, `focus`, `group-hover`...? 

Tank you, Florian.

**Comment by soueuls** [comment]
Hello @florianbouvot 

I might have messed up the package version number during deployment (it's the first time I do open source myself) but you should be good.

I added support for CSS color strings: 'blue', 'red', 'orangered' by using https://www.npmjs.com/package/color instead of my custom solution.

And all the variants are now supported for backgroundColor, borderColor(s), fill, stroke as well as textColor.

Only thing which is not supported is placeholderColor.

**Comment by florianbouvot** [comment]
@soueuls thank you very much, I think you can update your readme ;)
